version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ansible
    versions:
    - 2.10.6
    - 2.10.7
    - 3.2.0
