---
- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: all
  roles:
    - nfs
    - containerd
  tags:
    - supporting

- hosts: all
  roles:
    - kubernetes
  tags:
    - kubernetes
