- name: discover swap status
  ansible.builtin.shell: cat /proc/swaps | wc -l
  register: swap_out

- name: disable swap if enabled
  ansible.builtin.shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    systemctl disable dphys-swapfile
  when: swap_out.stdout != "1"

- name: enable memory cgroup
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^(.*) rootwait$'
    line: '\1 rootwait cgroup_enable=memory cgroup_memory=1'
    backrefs: yes

- name: reboot host
  ansible.builtin.shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
  async: 1
  poll: 0

- name: wait for host to come back up
  become: false
  ansible.builtin.wait_for_connection:
    delay: 15
    sleep: 2
    timeout: 120
